/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

const botKeywords = [
  'facebookexternalhit', 'facebot', 'messenger', 'whatsapp', 'telegrambot', 
  'twitterbot', 'discordbot', 'instagram', 'googlebot', 'bingbot', 'crawler', 'spider'
];

const isBot = (userAgent: string) => {
  const ua = userAgent.toLowerCase();
  return botKeywords.some(keyword => ua.includes(keyword));
};

// ImageKit Cache with Bot Block
registerRoute(
  ({ url }) => url.origin === 'https://ik.imagekit.io',
  new CacheFirst({
    cacheName: 'imagekit-cache',
    plugins: [
      {
        requestWillFetch: async ({ request }) => {
          // In some cases, UA is available on the request headers
          const ua = request.headers.get('User-Agent') || '';
          if (isBot(ua)) {
            return null; // Cancel fetch
          }
          return request;
        }
      },
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 60 * 60 * 24 * 60, // 60 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Google Fonts Cache
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache-v2',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365,
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'gstatic-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365,
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
